# Generated by Django 4.1.7 on 2023-05-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('create_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
