# Generated by Django 4.1.7 on 2023-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(max_length=1000)),
                ('img2', models.CharField(max_length=1000)),
                ('link1', models.CharField(max_length=1000)),
                ('link2', models.CharField(max_length=1000)),
                ('num', models.CharField(max_length=5)),
            ],
        ),
    ]
